spring.profiles.active=prod
app.url=https://www.autolaudos.com.br
spring.application.name=rvm

server.forward-headers-strategy=native
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

gateway.report=CheckTudo
mercadopago.api-url=https://api.mercadopago.com

# JPA / Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# Email
spring.mail.host=smtp.autolaudos.com.br
spring.mail.port=465
spring.mail.username=no-reply@autolaudos.com.br
spring.mail.password=5gJ}irJd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000