server.port=8080

# API Checktudo
api.checktudo.url= https://api.checktudo.com.br
api.checktudo.usuario=rafaelvmenezes@hotmail.com
api.checktudo.senha=Autolaudos@123

# MP Token
mercadopago.access-token=APP_USR-2374310020748375-033115-364a33aed3fc92e333e68c753e43f6d2-3305081189

# Datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/rvm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
#spring.datasource.username=root
#spring.datasource.password=Rgx071322!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://app-producao-mysql-ewxr.hospedagemelastica.com.br:3306/nnnrpdulyixa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=paeqyxxzkzsg
spring.datasource.password=zpvtyqourlarmvsdbnjqcewk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.open-in-view=false

#Logs
logging.file.name=logs/rvm-app.log
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR