# API Conferi
api.conferi.url=https://webservice.companyconferi.com.br/api-clientes-homologacao
api.conferi.usuario=123456
api.conferi.senha=password
api.conferi.agregados.url=/conferi-agregados?responseType=json
api.conferi.laudos.url=/conferi-veiculo?responseType=json
api.conferi.pdf.url=/gerar-pdf/

# API Checktudo
api.checktudo.url= https://api.checktudo.com.br
api.checktudo.usuario=rafaelvmenezes@hotmail.com
api.checktudo.senha=Autolaudos@123

# MP Token
mercadopago.access-token=TEST-2374310020748375-033115-abc79274660ab86fbbd44a81211b5bbf-3305081189

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/rvm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=Rgx071322!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
